### ISSUE TITLE
Add cppcheck ignore annotations for purely abstract classes

### ISSUE THREAD

**Issue by tbhova** [tbhova/YSU-Micromouse-SAC-2017#22]

**Comment by MrFobwatch** [comment]
I was trying to research how to add ignores. I was unsuccessful so far.

**Comment by tbhova** [comment]
CppCheck calls them suppressions
Page 11 of this manual http://cppcheck.sourceforge.net/manual.pdf

It should look something like the comments on this page for suppressing http://cppcheck.sourceforge.net/forum/viewtopic.php?f=4&t=154

**Comment by tbhova** [comment]
Turns out these warnings are the compiler and not cppCheck.
